name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build FastAPI Docker image
        run: |
          cd api
          docker build -t fastapi-app .

      - name: Build Next.js Docker image
        run: |
          cd front-end-nextjs
          docker build -t nextjs-app .

      - name: Tag FastAPI image
        run: |
          docker tag fastapi-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/fastapi-app:latest

      - name: Tag Next.js image
        run: |
          docker tag nextjs-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/nextjs-app:latest

      - name: Push FastAPI image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/fastapi-app:latest

      - name: Push Next.js image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/nextjs-app:latest
