name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
          --network=host

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build FastAPI Docker image
        run: |
          cd api
          docker build -t mohithgg14/fastapi-app .

      - name: Build Next.js Docker image
        run: |
          cd front-end-nextjs
          docker build -t mohithgg14/nextjs-app .

      - name: Push FastAPI image
        run: docker push mohithgg14/fastapi-app

      - name: Push Next.js image
        run: docker push mohithgg14/nextjs-app
