name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
          --network=host

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: front-end-nextjs/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front-end-nextjs/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('api/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run FastAPI tests
        run: |
          cd api
          pip install -r requirements.txt
          pytest  # Run your FastAPI tests

      - name: Run Next.js tests
        run: |
          cd front-end-nextjs
          npm install
          npm test  # Run your Next.js tests

      - name: Build FastAPI Docker image
        run: |
          cd api
          docker build -t mohithgg14/fastapi-app:${{ github.sha }} .

      - name: Build Next.js Docker image
        run: |
          cd front-end-nextjs
          docker build -t mohithgg14/nextjs-app:${{ github.sha }} .

      - name: Push FastAPI image
        run: docker push mohithgg14/fastapi-app:${{ github.sha }}

      - name: Push Next.js image
        run: docker push mohithgg14/nextjs-app:${{ github.sha }}
